export const beaches = [
  { name: 'Marina Beach', district: 'Chennai', coordinates: { lat: 13.0500, lng: 80.2824 }, image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=85', description: 'A long urban beach along the Chennai coast with major access points and visitor facilities.', tags: ['city', 'family', 'sunrise'], lifeguard: { status: 'On Duty', dutyHours: '06:00 AM – 06:00 PM', towers: 3, nearestTowerMeters: 320 }, safety: { alertLevel: 'yellow', label: 'Caution', reason: 'Moderate wave conditions in the demo safety feed.', source: 'BeachSafe demo safety data' } },
  { name: "Elliot's Beach", district: 'Chennai', coordinates: { lat: 12.9976, lng: 80.2707 }, image: 'https://images.unsplash.com/photo-1519046904884-53103b34b206?auto=format&fit=crop&w=1200&q=85', description: 'A popular Chennai beach known for its calm promenade areas and neighbourhood access.', tags: ['family', 'promenade'], lifeguard: { status: 'On Duty', dutyHours: '06:00 AM – 06:00 PM', towers: 2, nearestTowerMeters: 270 }, safety: { alertLevel: 'green', label: 'No active advisory', reason: 'No application-level advisory is recorded.', source: 'BeachSafe demo safety data' } },
  { name: 'Kovalam Beach', district: 'Chengalpattu', coordinates: { lat: 12.7934, lng: 80.2536 }, image: 'https://images.unsplash.com/photo-1473116763249-2faaef81ccda?auto=format&fit=crop&w=1200&q=85', description: 'A coastal destination near Chennai with surfing, fishing and visitor facilities.', tags: ['surfing', 'fishing'], lifeguard: { status: 'On Duty', dutyHours: '07:00 AM – 06:00 PM', towers: 2, nearestTowerMeters: 190 }, safety: { alertLevel: 'yellow', label: 'Caution', reason: 'Wind and wave conditions should be checked before entering the water.', source: 'BeachSafe demo safety data' } },
  { name: 'Mahabalipuram Beach', district: 'Chengalpattu', coordinates: { lat: 12.6196, lng: 80.1945 }, image: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=85', description: 'A heritage-coast destination near the Shore Temple area.', tags: ['heritage', 'tourism'], lifeguard: { status: 'On Duty', dutyHours: '06:00 AM – 06:00 PM', towers: 2, nearestTowerMeters: 410 }, safety: { alertLevel: 'green', label: 'No active advisory', reason: 'No application-level advisory is recorded.', source: 'BeachSafe demo safety data' } },
  { name: 'Besant Nagar Beach', district: 'Chennai', coordinates: { lat: 13.0002, lng: 80.2662 }, image: 'https://images.unsplash.com/photo-1500375592092-40eb2168fd21?auto=format&fit=crop&w=1200&q=85', description: 'An accessible urban beach area popular with Chennai residents.', tags: ['city', 'food'], lifeguard: { status: 'On Duty', dutyHours: '06:00 AM – 06:00 PM', towers: 2, nearestTowerMeters: 340 }, safety: { alertLevel: 'green', label: 'No active advisory', reason: 'No application-level advisory is recorded.', source: 'BeachSafe demo safety data' } },
  { name: 'Poompuhar Beach', district: 'Mayiladuthurai', coordinates: { lat: 11.1447, lng: 79.8481 }, image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80', description: 'A historic coastal destination on the Cauvery delta coast.', tags: ['heritage', 'sunset'], lifeguard: { status: 'Limited', dutyHours: '08:00 AM – 05:00 PM', towers: 1, nearestTowerMeters: 540 }, safety: { alertLevel: 'yellow', label: 'Caution', reason: 'Verify current local conditions before entering the water.', source: 'BeachSafe demo safety data' } },
  { name: 'Tharangambadi Beach', district: 'Mayiladuthurai', coordinates: { lat: 11.0266, lng: 79.8540 }, image: 'https://images.unsplash.com/photo-1493552152660-f915ab47ae9d?auto=format&fit=crop&w=1200&q=80', description: 'A heritage coastal town with beachfront and historic architecture.', tags: ['heritage', 'family'], lifeguard: { status: 'Limited', dutyHours: '08:00 AM – 05:00 PM', towers: 1, nearestTowerMeters: 460 }, safety: { alertLevel: 'green', label: 'No active advisory', reason: 'No application-level advisory is recorded.', source: 'BeachSafe demo safety data' } },
  { name: 'Nagapattinam Beach', district: 'Nagapattinam', coordinates: { lat: 10.7600, lng: 79.8449 }, image: 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=1200&q=80', description: 'Urban coastal access in Nagapattinam district.', tags: ['city', 'sunset'], lifeguard: { status: 'On Duty', dutyHours: '06:00 AM – 06:00 PM', towers: 2, nearestTowerMeters: 380 }, safety: { alertLevel: 'yellow', label: 'Caution', reason: 'Local safety status should be checked before water entry.', source: 'BeachSafe demo safety data' } },
  { name: 'Velankanni Beach', district: 'Nagapattinam', coordinates: { lat: 10.6817, lng: 79.8430 }, image: 'https://images.unsplash.com/photo-1494783367193-149034c05e8f?auto=format&fit=crop&w=1200&q=80', description: 'A coastal visitor destination near Velankanni.', tags: ['pilgrimage', 'family'], lifeguard: { status: 'Limited', dutyHours: '08:00 AM – 05:00 PM', towers: 1, nearestTowerMeters: 510 }, safety: { alertLevel: 'green', label: 'No active advisory', reason: 'No application-level advisory is recorded.', source: 'BeachSafe demo safety data' } },
  { name: 'Silver Beach', district: 'Cuddalore', coordinates: { lat: 11.7049, lng: 79.7698 }, image: 'https://images.unsplash.com/photo-1493552152660-f915ab47ae9d?auto=format&fit=crop&w=1200&q=80', description: 'A broad sandy beach destination near Cuddalore town.', tags: ['family', 'picnic'], lifeguard: { status: 'On Duty', dutyHours: '07:00 AM – 06:00 PM', towers: 2, nearestTowerMeters: 290 }, safety: { alertLevel: 'green', label: 'No active advisory', reason: 'No application-level advisory is recorded.', source: 'BeachSafe demo safety data' } },
  { name: 'Pichavaram Beach', district: 'Cuddalore', coordinates: { lat: 11.4300, lng: 79.7897 }, image: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=80', description: 'A coastal destination associated with the Pichavaram mangrove region.', tags: ['nature', 'boat'], lifeguard: { status: 'Limited', dutyHours: '08:00 AM – 05:00 PM', towers: 1, nearestTowerMeters: 900 }, safety: { alertLevel: 'yellow', label: 'Caution', reason: 'Check local access and sea conditions before water activities.', source: 'BeachSafe demo safety data' } },
  { name: 'Rameswaram Beach', district: 'Ramanathapuram', coordinates: { lat: 9.2885, lng: 79.3129 }, image: 'https://images.unsplash.com/photo-1476673160081-cf065607f449?auto=format&fit=crop&w=1200&q=80', description: 'A major pilgrimage and coastal tourism destination.', tags: ['pilgrimage', 'tourism'], lifeguard: { status: 'On Duty', dutyHours: '06:00 AM – 06:00 PM', towers: 2, nearestTowerMeters: 360 }, safety: { alertLevel: 'green', label: 'No active advisory', reason: 'No application-level advisory is recorded.', source: 'BeachSafe demo safety data' } },
  { name: 'Dhanushkodi Beach', district: 'Ramanathapuram', coordinates: { lat: 9.1684, lng: 79.4316 }, image: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80', description: 'An exposed coastal destination at the southeastern tip of Rameswaram island.', tags: ['nature', 'heritage'], lifeguard: { status: 'Limited', dutyHours: '08:00 AM – 04:00 PM', towers: 1, nearestTowerMeters: 1200 }, safety: { alertLevel: 'yellow', label: 'Caution', reason: 'Remote conditions require extra attention to local advisories.', source: 'BeachSafe demo safety data' } },
  { name: 'Kanyakumari Beach', district: 'Kanniyakumari', coordinates: { lat: 8.0780, lng: 77.5551 }, image: 'https://images.unsplash.com/photo-1476673160081-cf065607f449?auto=format&fit=crop&w=1200&q=80', description: 'India’s southern tip with sunrise and sunset viewpoints.', tags: ['tourism', 'sunrise'], lifeguard: { status: 'On Duty', dutyHours: '06:00 AM – 06:00 PM', towers: 2, nearestTowerMeters: 450 }, safety: { alertLevel: 'yellow', label: 'Caution', reason: 'Check current sea conditions before entering the water.', source: 'BeachSafe demo safety data' } },
  { name: 'Sanguthurai Beach', district: 'Kanniyakumari', coordinates: { lat: 8.1722, lng: 77.3797 }, image: 'https://images.unsplash.com/photo-1494783367193-149034c05e8f?auto=format&fit=crop&w=1200&q=80', description: 'A quieter coastal destination in Kanniyakumari district.', tags: ['quiet', 'sunset'], lifeguard: { status: 'Limited', dutyHours: '08:00 AM – 05:00 PM', towers: 1, nearestTowerMeters: 700 }, safety: { alertLevel: 'green', label: 'No active advisory', reason: 'No application-level advisory is recorded.', source: 'BeachSafe demo safety data' } },
  { name: 'Manapad Beach', district: 'Thoothukudi', coordinates: { lat: 8.3758, lng: 78.0517 }, image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80', description: 'A coastal village with scenic shorelines and a historic setting.', tags: ['quiet', 'heritage'], lifeguard: { status: 'Limited', dutyHours: '08:00 AM – 05:00 PM', towers: 1, nearestTowerMeters: 800 }, safety: { alertLevel: 'yellow', label: 'Caution', reason: 'Check local conditions and access information before water entry.', source: 'BeachSafe demo safety data' } },
  { name: 'Tuticorin Beach', district: 'Thoothukudi', coordinates: { lat: 8.7832, lng: 78.1348 }, image: 'https://images.unsplash.com/photo-1500375592092-40eb2168fd21?auto=format&fit=crop&w=1200&q=80', description: 'Coastal urban access near Thoothukudi.', tags: ['city', 'sunset'], lifeguard: { status: 'On Duty', dutyHours: '07:00 AM – 06:00 PM', towers: 2, nearestTowerMeters: 440 }, safety: { alertLevel: 'green', label: 'No active advisory', reason: 'No application-level advisory is recorded.', source: 'BeachSafe demo safety data' } }
];

export const facilityTypes = ['Hotel', 'Restaurant', 'Restroom', 'Parking', 'First Aid', 'Drinking Water', 'Accessible Access', 'Lifeguard'];

export function makeFacilities(beach, beachId = null) {
  const multipliers = [
    ['Beach View Hotel', 'Hotel', 700],
    ['Seaside Restaurant', 'Restaurant', 420],
    ['Public Restroom', 'Restroom', 280],
    ['Beach Parking', 'Parking', 520],
    ['First Aid Point', 'First Aid', 360],
    ['Drinking Water Point', 'Drinking Water', 240],
    ['Accessible Entrance', 'Accessible Access', 310],
    ['Main Lifeguard Tower', 'Lifeguard', beach.lifeguard?.nearestTowerMeters || 320]
  ];
  return multipliers.map(([name, type, distance], idx) => ({
    _id: `${beachId || beach.name}-${idx}`,
    beachId,
    name,
    type,
    distanceMeters: distance,
    address: `${beach.name} visitor area`,
    coordinates: { lat: beach.coordinates.lat + (idx % 2 ? 0.001 : -0.001), lng: beach.coordinates.lng + (idx % 3 ? 0.001 : -0.001) }
  }));
}

export const defaultAlerts = [
  { title: 'Strong wind advisory', severity: 'caution', description: 'Exercise care near open shore areas and follow local beach instructions.', source: 'BeachSafe demo data' },
  { title: 'High wave information', severity: 'high', description: 'Water entry should follow current local authority and lifeguard guidance.', source: 'BeachSafe demo data' }
];
